### ISSUE TITLE
Ensure summary QC file has all of the Inspect metadata and GISAID upload required

### ISSUE THREAD

**Issue by kmfisch** [ucsd-ccbb/covid_sequencing_analysis_pipeline#61] opened 2021-03-19 20:53 UTC
-Depends on communication with Shashank for Inspect
-Depends on communication with Andersen lab for upload requirements

**Comment by kmfisch** [comment] 2021-03-19 21:32
On Mar 19, 2021, at 10:47 AM, Laurent, Louise <llaurent@health.ucsd.edu> wrote:

Hi,

Thank you for this call. I think it was very helpful in understanding how we can proceed with reporting results in a useful and principled manner. Here are some notes:
We will report 3 categories of viral sequencing results (please provide feedback on wording):
For samples with <70% coverage OR do not pass Pangolin lineage calling QC: "SARS-CoV-2 viral genome sequencing was performed. However, viral genome data obtained were not sufficient for viral variant determination or viral epidemiology analyses." [Lineage field and SEARCH ID field are empty]
For samples with 70-95% coverage AND pass Pangolin lineage calling QC: "SARS-CoV-2 viral genome sequencing was performed. Viral genome data obtained are sufficient for viral variant determination, but not comprehensive enough for inclusion in viral epidemiology analyses." [Lineage field is filled, but SEARCH ID field is empty]
For samples with >95% coverage AND pass Pangolin lineage calling QC: "SARS-CoV-2 viral genome sequencing was performed. Viral genome data obtained are comprehensive and sufficient for viral variant determination and inclusion in viral epidemiology analyses." [Lineage field and SEARCH ID field are filled]
Allen's team and Sashank will work to make sure the interface handles these categories properly (perhaps it would be good for Francesca/Chip/me to review some screenshots of test results as they would appear in the Results section of EPIC).
A current set of data are being analyzed currently. Once it is completed, we will annotate into these three categories and share with this group for review.
The legacy data will be reanalyzed and annotated, likely next week.
Please send any questions or comments.

Have a great weekend!
Louise

**Comment by AmandaBirmingham** [comment] 2021-03-19 22:29
Closed as duplicate of #58

**Closed by AmandaBirmingham** 2021-03-19 22:29 UTC
Labels: enhancement, next release priority
